# Generated by Django 5.0.3 on 2024-03-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shaqada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaqada', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=250)),
                ('zoone', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion', models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], default='None', max_length=200)),
                ('shaqada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_register.shaqada')),
            ],
        ),
    ]
