# Generated by Django 5.0.3 on 2024-03-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memo',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
