# Generated by Django 5.0.3 on 2024-03-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_register', '0002_task_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.TextField(max_length=400),
        ),
    ]
