# Generated by Django 5.0.3 on 2024-03-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_register', '0003_alter_task_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='memo',
        ),
    ]
