# Generated by Django 5.0.3 on 2024-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_register', '0004_remove_task_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
    ]
