# Generated by Django 5.0.3 on 2024-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_register', '0005_task_memo_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
